### ISSUE TITLE
训练baichuan2 13b 报 KeyError: 'instruction'

### ISSUE THREAD

**Issue by joymcg** [alibaba/Pai-Megatron-Patch#102]
`

building BaichuanTokenizer tokenizer ...
Traceback (most recent call last):
  File "/GPU/Pai-Megatron-Patch/examples/baichuan2/pretrain_megatron_baichuan.py", line 125, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider,
  File "/GPU/Pai-Megatron-Patch/megatron_patch/training.py", line 133, in pretrain
    = build_train_valid_test_data_iterators(
  File "/GPU/Pai-Megatron-Patch/Megatron-LM-main/megatron/training.py", line 1005, in build_train_valid_test_data_iterators
    build_train_valid_test_data_loaders(
  File "/GPU/Pai-Megatron-Patch/Megatron-LM-main/megatron/training.py", line 963, in build_train_valid_test_data_loaders
    train_ds, valid_ds, test_ds = build_train_valid_test_datasets(
  File "/GPU/Pai-Megatron-Patch/Megatron-LM-main/megatron/training.py", line 936, in build_train_valid_test_datasets
    return build_train_valid_test_datasets_provider(train_val_test_num_samples)
  File "/GPU/Pai-Megatron-Patch/examples/baichuan2/pretrain_megatron_baichuan.py", line 107, in train_valid_test_datasets_provider
    build_pretrain_dataset_from_original(args.dataset)
  File "GPU/Pai-Megatron-Patch/megatron_patch/data/__init__.py", line 69, in build_pretrain_dataset_from_original
    train_dataset = LLamaRawDataset(args.train_data_path, args.max_padding_length)
  File "/Pai-Megatron-Patch/megatron_patch/data/llama.py", line 52, in __init__
    sources = [
  File "/Pai-Megatron-Patch/megatron_patch/data/llama.py", line 54, in <listcomp>
    else prompt_no_input.format_map(example)
KeyError: 'instruction'

`
之前还有一个  attention_softmax_in_fp32 找不到，我删了代码

**Comment by lwmlyy** [comment]
数据集格式参考https://github.com/tatsu-lab/stanford_alpaca/blob/main/alpaca_data.json

**Comment by joymcg** [comment]
> 数据集格式参考https://github.com/tatsu-lab/stanford_alpaca/blob/main/alpaca_data.json

您好，感谢回复
换了数据集报如下的错误， 有没有针对baichuan 的教程？ 另外问下 --dataset 参数是干啥的，我看预训练默认带上了那个参数， 但是没有相关说明。

File "/GPU/Pai-Megatron-Patch/examples/baichuan2/pretrain_megatron_baichuan.py", line 125, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider,
  File "/GPU/Pai-Megatron-Patch/megatron_patch/training.py", line 133, in pretrain
    = build_train_valid_test_data_iterators(
  File "/GPU/Pai-Megatron-Patch/Megatron-LM-main/megatron/training.py", line 1005, in build_train_valid_test_data_iterators
    build_train_valid_test_data_loaders(
  File "/GPU/Pai-Megatron-Patch/Megatron-LM-main/megatron/training.py", line 963, in build_train_valid_test_data_loaders
    train_ds, valid_ds, test_ds = build_train_valid_test_datasets(
  File "/GPU/Pai-Megatron-Patch/Megatron-LM-main/megatron/training.py", line 936, in build_train_valid_test_datasets
    return build_train_valid_test_datasets_provider(train_val_test_num_samples)
  File "/GPU/Pai-Megatron-Patch/examples/baichuan2/pretrain_megatron_baichuan.py", line 107, in train_valid_test_datasets_provider
    build_pretrain_dataset_from_original(args.dataset)
  File "/GPU/Pai-Megatron-Patch/megatron_patch/data/__init__.py", line 70, in build_pretrain_dataset_from_original
    valid_dataset = LLamaRawDataset(args.valid_data_path, args.max_padding_length)
  File "/GPU/Pai-Megatron-Patch/megatron_patch/data/llama.py", line 48, in __init__
    list_data_dict = self.jload(path[0])
TypeError: 'NoneType' object is not subscriptable

**Comment by lwmlyy** [comment]
需要同时传入一个验证集数据。

--dataset用于区分预训练及微调中使用到的不同数据类型，详细代码可以参考[这里](https://github.com/alibaba/Pai-Megatron-Patch/blob/main/megatron_patch/data/__init__.py)。

教程可参考[千问](https://help.aliyun.com/zh/pai/use-cases/train-fine-tune-and-deploy-qwen-by-using-intelligent-computing-lingjun?spm=5176.21213303.J_qCOwPWspKEuWcmp8qiZNQ.1.75462f3dlVxoIf&scm=20140722.S_help@@%E6%96%87%E6%A1%A3@@2636027._.ID_help@@%E6%96%87%E6%A1%A3@@2636027-RL_%E9%80%9A%E4%B9%89%E5%8D%83%E9%97%AE%E5%BC%80%E6%BA%90%E6%A8%A1%E5%9E%8B%E5%9C%A8pai%E7%81%B5%E9%AA%8F%E7%9A%84%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5-LOC_llm-OR_ser-V_3-RK_rerank-P0_0)

**Comment by joymcg** [comment]
> 需要同时传入一个验证集数据。
> 
> --dataset用于区分预训练及微调中使用到的不同数据类型，详细代码可以参考[这里](https://github.com/alibaba/Pai-Megatron-Patch/blob/main/megatron_patch/data/__init__.py)。
> 
> 教程可参考[千问](https://help.aliyun.com/zh/pai/use-cases/train-fine-tune-and-deploy-qwen-by-using-intelligent-computing-lingjun?spm=5176.21213303.J_qCOwPWspKEuWcmp8qiZNQ.1.75462f3dlVxoIf&scm=20140722.S_help@@%E6%96%87%E6%A1%A3@@2636027._.ID_help@@%E6%96%87%E6%A1%A3@@2636027-RL_%E9%80%9A%E4%B9%89%E5%8D%83%E9%97%AE%E5%BC%80%E6%BA%90%E6%A8%A1%E5%9E%8B%E5%9C%A8pai%E7%81%B5%E9%AA%8F%E7%9A%84%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5-LOC_llm-OR_ser-V_3-RK_rerank-P0_0)

多谢，已经跑起来了
