### ISSUE TITLE
Pretrain megatron qwen-7b-tp4-pp1 报错 151851 is not divisible by 4

### ISSUE THREAD

**Issue by KannbaraQRS** [alibaba/Pai-Megatron-Patch#103]
AssertionError: 151851 is not divisible by 4
Traceback (most recent call last):
  File "/home/nlp/shi/megatron/Pai-Megatron-Patch/examples/qwen/pretrain_megatron_qwen.py", line 125, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider,
  File "/home/nlp/shi/megatron/Pai-Megatron-Patch/megatron_patch/training.py", line 109, in pretrain
    model, optimizer, opt_param_scheduler = setup_model_and_optimizer(
  File "/home/nlp/shi/megatron/Pai-Megatron-Patch/megatron_patch/training.py", line 327, in setup_model_and_optimizer
    model = get_model(model_provider_func, model_type)
  File "/home/nlp/shi/megatron/Pai-Megatron-Patch/megatron_patch/training.py", line 256, in get_model
    model = model_provider_func(
  File "/home/nlp/shi/megatron/Pai-Megatron-Patch/examples/qwen/pretrain_megatron_qwen.py", line 38, in model_provider
    model = GPTModel(
  File "/home/nlp/shi/megatron/Pai-Megatron-Patch/megatron_patch/model/qwen/gpt_model.py", line 71, in __init__
    self.language_model, self._language_model_key = get_language_model(
  File "/home/nlp/shi/megatron/Pai-Megatron-Patch/megatron_patch/model/qwen/language_model.py", line 77, in get_language_model
    language_model = TransformerLanguageModel(
  File "/home/nlp/shi/megatron/Pai-Megatron-Patch/megatron_patch/model/qwen/language_model.py", line 363, in __init__
    self.embedding = Embedding(self.hidden_size,
  File "/home/nlp/shi/megatron/Pai-Megatron-Patch/megatron_patch/model/qwen/language_model.py", line 161, in __init__
    self.word_embeddings = tensor_parallel.VocabParallelEmbedding(
  File "/home/nlp/shi/megatron/Pai-Megatron-Patch/Megatron-LM-main/megatron/core/tensor_parallel/layers.py", line 171, in __init__
    ) = VocabUtility.vocab_range_from_global_vocab_size(
  File "/home/nlp/shi/megatron/Pai-Megatron-Patch/Megatron-LM-main/megatron/core/tensor_parallel/utils.py", line 110, in vocab_range_from_global_vocab_size
    per_partition_vocab_size = divide(global_vocab_size, world_size)
  File "/home/nlp/shi/megatron/Pai-Megatron-Patch/Megatron-LM-main/megatron/core/utils.py", line 22, in divide
    ensure_divisibility(numerator, denominator)
  File "/home/nlp/shi/megatron/Pai-Megatron-Patch/Megatron-LM-main/megatron/core/utils.py", line 16, in ensure_divisibility
    assert numerator % denominator == 0, "{} is not divisible by {}".format(numerator, denominator)

个人觉得应该是 configuration_qwen.py 中 vocab_size 的问题。我看官方的Qwen7B词表为151936，但是即使我修改了文件中的vocab_size 为 151936之后再次尝试，依然是这个报错。请问该如何解决。

**Comment by ShuMengZ** [comment]
EXTRA_VOCAB_SIZE=${10}          # 词表扩充大小：7B使用85，14B和72B模型填213

**Comment by KannbaraQRS** [comment]
> EXTRA_VOCAB_SIZE=${10} # 词表扩充大小：7B使用85，14B和72B模型填213

感谢帮助
