### ISSUE TITLE
megatron转huggingface报错

### ISSUE THREAD

**Issue by Jayce1kk** [alibaba/Pai-Megatron-Patch#156]
我将huggingface格式的qwen1.5-0.5B模型转为megatron格式之后，在megatron框架下进行训练。在将训练得到的权重转为huggingface时出现了以下错误：
```shell
2024-03-18 11:09:50.106230: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-18 11:09:50.109118: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-18 11:09:50.142500: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-18 11:09:50.142556: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-18 11:09:50.142599: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-18 11:09:50.149803: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-18 11:09:50.920300: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading Megatron-LM checkpoint arguments from: /mnt/raid/xujianjun/LLM_train/wjk/Megatron-LM/checkpoints/Qwen-1.5-0.5B_1/release/mp_rank_00/model_optim_rng.pt
Zarr-based strategies will not be registered because of missing packages
cp: target '/mnt/raid/xujianjun/LLM_train/wjk/Megatron-LM/checkpoints/models--Qwen--Qwen1.5-0.5B-mg2hf41-aftertrain1_test/' is not a directory
cp: cannot stat '/mnt/raid/xujianjun/LLM_train/wjk/Megatron-LM/checkpoints/Qwen-1.5-0.5B_1/tokenizer.model': No such file or directory
Converting
Converting embeddings
Converting transformer layers
Converting pipeline parallel rank 0
model.layers.0 input_norm weight
model.layers.0 self_attention.query_key_value weight
model.layers.0 self_attention.query_key_value bias
model.layers.0 self_attention query
Traceback (most recent call last):
  File "/mnt/raid/xujianjun/LLM_train/wjk/Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/qwen/checkpoint_reshaping_and_interoperability_qwen1.5.py", line 994, in <module>
    main()
  File "/mnt/raid/xujianjun/LLM_train/wjk/Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/qwen/checkpoint_reshaping_and_interoperability_qwen1.5.py", line 988, in main
    convert_checkpoint_from_megatron_to_transformers(args)
  File "/mnt/raid/xujianjun/LLM_train/wjk/Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/qwen/checkpoint_reshaping_and_interoperability_qwen1.5.py", line 843, in convert_checkpoint_from_megatron_to_transformers
    params = val.to(dtype)
             ^^^^^^
AttributeError: 'NoneType' object has no attribute 'to'
``` 

然后我将报错的层用‘error’为前缀打印出来，结果如下：

```shell
2024-03-18 11:10:46.456280: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-18 11:10:46.459179: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-18 11:10:46.492705: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-18 11:10:46.492756: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-18 11:10:46.492795: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-18 11:10:46.499963: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-18 11:10:47.273311: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Loading Megatron-LM checkpoint arguments from: /mnt/raid/xujianjun/LLM_train/wjk/Megatron-LM/checkpoints/Qwen-1.5-0.5B_1/release/mp_rank_00/model_optim_rng.pt
Zarr-based strategies will not be registered because of missing packages
cp: target '/mnt/raid/xujianjun/LLM_train/wjk/Megatron-LM/checkpoints/models--Qwen--Qwen1.5-0.5B-mg2hf41-aftertrain1_test/' is not a directory
cp: cannot stat '/mnt/raid/xujianjun/LLM_train/wjk/Megatron-LM/checkpoints/Qwen-1.5-0.5B_1/tokenizer.model': No such file or directory
Converting
Converting embeddings
Converting transformer layers
Converting pipeline parallel rank 0
model.layers.0 input_norm weight
model.layers.0 self_attention.query_key_value weight
model.layers.0 self_attention.query_key_value bias
model.layers.0 self_attention query
error: self_attention.query
model.layers.0 self_attention.dense weight
model.layers.0 self_attention dense
error: self_attention.dense
model.layers.0 post_attention_norm weight
model.layers.0 mlp.dense_h_to_4h weight
model.layers.0 mlp dense
error: mlp.dense
model.layers.0 mlp.dense_4h_to_h weight
model.layers.0 mlp dense
error: mlp.dense
model.layers.1 input_norm weight
model.layers.1 self_attention.query_key_value weight
model.layers.1 self_attention.query_key_value bias
model.layers.1 self_attention query
error: self_attention.query
model.layers.1 self_attention.dense weight
model.layers.1 self_attention dense
error: self_attention.dense
model.layers.1 post_attention_norm weight
model.layers.1 mlp.dense_h_to_4h weight
model.layers.1 mlp dense
error: mlp.dense
model.layers.1 mlp.dense_4h_to_h weight
model.layers.1 mlp dense
error: mlp.dense
model.layers.2 input_norm weight
model.layers.2 self_attention.query_key_value weight
model.layers.2 self_attention.query_key_value bias
model.layers.2 self_attention query
error: self_attention.query
model.layers.2 self_attention.dense weight
model.layers.2 self_attention dense
error: self_attention.dense
model.layers.2 post_attention_norm weight
model.layers.2 mlp.dense_h_to_4h weight
model.layers.2 mlp dense
error: mlp.dense
model.layers.2 mlp.dense_4h_to_h weight
model.layers.2 mlp dense
error: mlp.dense
model.layers.3 input_norm weight
model.layers.3 self_attention.query_key_value weight
model.layers.3 self_attention.query_key_value bias
model.layers.3 self_attention query
error: self_attention.query
model.layers.3 self_attention.dense weight
model.layers.3 self_attention dense
error: self_attention.dense
model.layers.3 post_attention_norm weight
model.layers.3 mlp.dense_h_to_4h weight
model.layers.3 mlp dense
error: mlp.dense
model.layers.3 mlp.dense_4h_to_h weight
model.layers.3 mlp dense
error: mlp.dense
model.layers.4 input_norm weight
model.layers.4 self_attention.query_key_value weight
model.layers.4 self_attention.query_key_value bias
model.layers.4 self_attention query
error: self_attention.query
model.layers.4 self_attention.dense weight
model.layers.4 self_attention dense
error: self_attention.dense
model.layers.4 post_attention_norm weight
model.layers.4 mlp.dense_h_to_4h weight
model.layers.4 mlp dense
error: mlp.dense
model.layers.4 mlp.dense_4h_to_h weight
model.layers.4 mlp dense
error: mlp.dense
model.layers.5 input_norm weight
model.layers.5 self_attention.query_key_value weight
model.layers.5 self_attention.query_key_value bias
model.layers.5 self_attention query
error: self_attention.query
model.layers.5 self_attention.dense weight
model.layers.5 self_attention dense
error: self_attention.dense
model.layers.5 post_attention_norm weight
model.layers.5 mlp.dense_h_to_4h weight
model.layers.5 mlp dense
error: mlp.dense
model.layers.5 mlp.dense_4h_to_h weight
model.layers.5 mlp dense
error: mlp.dense
model.layers.6 input_norm weight
model.layers.6 self_attention.query_key_value weight
model.layers.6 self_attention.query_key_value bias
model.layers.6 self_attention query
error: self_attention.query
model.layers.6 self_attention.dense weight
model.layers.6 self_attention dense
error: self_attention.dense
model.layers.6 post_attention_norm weight
model.layers.6 mlp.dense_h_to_4h weight
model.layers.6 mlp dense
error: mlp.dense
model.layers.6 mlp.dense_4h_to_h weight
model.layers.6 mlp dense
error: mlp.dense
model.layers.7 input_norm weight
model.layers.7 self_attention.query_key_value weight
model.layers.7 self_attention.query_key_value bias
model.layers.7 self_attention query
error: self_attention.query
model.layers.7 self_attention.dense weight
model.layers.7 self_attention dense
error: self_attention.dense
model.layers.7 post_attention_norm weight
model.layers.7 mlp.dense_h_to_4h weight
model.layers.7 mlp dense
error: mlp.dense
model.layers.7 mlp.dense_4h_to_h weight
model.layers.7 mlp dense
error: mlp.dense
model.layers.8 input_norm weight
model.layers.8 self_attention.query_key_value weight
model.layers.8 self_attention.query_key_value bias
model.layers.8 self_attention query
error: self_attention.query
model.layers.8 self_attention.dense weight
model.layers.8 self_attention dense
error: self_attention.dense
model.layers.8 post_attention_norm weight
model.layers.8 mlp.dense_h_to_4h weight
model.layers.8 mlp dense
error: mlp.dense
model.layers.8 mlp.dense_4h_to_h weight
model.layers.8 mlp dense
error: mlp.dense
model.layers.9 input_norm weight
model.layers.9 self_attention.query_key_value weight
model.layers.9 self_attention.query_key_value bias
model.layers.9 self_attention query
error: self_attention.query
model.layers.9 self_attention.dense weight
model.layers.9 self_attention dense
error: self_attention.dense
model.layers.9 post_attention_norm weight
model.layers.9 mlp.dense_h_to_4h weight
model.layers.9 mlp dense
error: mlp.dense
model.layers.9 mlp.dense_4h_to_h weight
model.layers.9 mlp dense
error: mlp.dense
model.layers.10 input_norm weight
model.layers.10 self_attention.query_key_value weight
model.layers.10 self_attention.query_key_value bias
model.layers.10 self_attention query
error: self_attention.query
model.layers.10 self_attention.dense weight
model.layers.10 self_attention dense
error: self_attention.dense
model.layers.10 post_attention_norm weight
model.layers.10 mlp.dense_h_to_4h weight
model.layers.10 mlp dense
error: mlp.dense
model.layers.10 mlp.dense_4h_to_h weight
model.layers.10 mlp dense
error: mlp.dense
model.layers.11 input_norm weight
model.layers.11 self_attention.query_key_value weight
model.layers.11 self_attention.query_key_value bias
model.layers.11 self_attention query
error: self_attention.query
model.layers.11 self_attention.dense weight
model.layers.11 self_attention dense
error: self_attention.dense
model.layers.11 post_attention_norm weight
model.layers.11 mlp.dense_h_to_4h weight
model.layers.11 mlp dense
error: mlp.dense
model.layers.11 mlp.dense_4h_to_h weight
model.layers.11 mlp dense
error: mlp.dense
model.layers.12 input_norm weight
model.layers.12 self_attention.query_key_value weight
model.layers.12 self_attention.query_key_value bias
model.layers.12 self_attention query
error: self_attention.query
model.layers.12 self_attention.dense weight
model.layers.12 self_attention dense
error: self_attention.dense
model.layers.12 post_attention_norm weight
model.layers.12 mlp.dense_h_to_4h weight
model.layers.12 mlp dense
error: mlp.dense
model.layers.12 mlp.dense_4h_to_h weight
model.layers.12 mlp dense
error: mlp.dense
model.layers.13 input_norm weight
model.layers.13 self_attention.query_key_value weight
model.layers.13 self_attention.query_key_value bias
model.layers.13 self_attention query
error: self_attention.query
model.layers.13 self_attention.dense weight
model.layers.13 self_attention dense
error: self_attention.dense
model.layers.13 post_attention_norm weight
model.layers.13 mlp.dense_h_to_4h weight
model.layers.13 mlp dense
error: mlp.dense
model.layers.13 mlp.dense_4h_to_h weight
model.layers.13 mlp dense
error: mlp.dense
model.layers.14 input_norm weight
model.layers.14 self_attention.query_key_value weight
model.layers.14 self_attention.query_key_value bias
model.layers.14 self_attention query
error: self_attention.query
model.layers.14 self_attention.dense weight
model.layers.14 self_attention dense
error: self_attention.dense
model.layers.14 post_attention_norm weight
model.layers.14 mlp.dense_h_to_4h weight
model.layers.14 mlp dense
error: mlp.dense
model.layers.14 mlp.dense_4h_to_h weight
model.layers.14 mlp dense
error: mlp.dense
model.layers.15 input_norm weight
model.layers.15 self_attention.query_key_value weight
model.layers.15 self_attention.query_key_value bias
model.layers.15 self_attention query
error: self_attention.query
model.layers.15 self_attention.dense weight
model.layers.15 self_attention dense
error: self_attention.dense
model.layers.15 post_attention_norm weight
model.layers.15 mlp.dense_h_to_4h weight
model.layers.15 mlp dense
error: mlp.dense
model.layers.15 mlp.dense_4h_to_h weight
model.layers.15 mlp dense
error: mlp.dense
model.layers.16 input_norm weight
model.layers.16 self_attention.query_key_value weight
model.layers.16 self_attention.query_key_value bias
model.layers.16 self_attention query
error: self_attention.query
model.layers.16 self_attention.dense weight
model.layers.16 self_attention dense
error: self_attention.dense
model.layers.16 post_attention_norm weight
model.layers.16 mlp.dense_h_to_4h weight
model.layers.16 mlp dense
error: mlp.dense
model.layers.16 mlp.dense_4h_to_h weight
model.layers.16 mlp dense
error: mlp.dense
model.layers.17 input_norm weight
model.layers.17 self_attention.query_key_value weight
model.layers.17 self_attention.query_key_value bias
model.layers.17 self_attention query
error: self_attention.query
model.layers.17 self_attention.dense weight
model.layers.17 self_attention dense
error: self_attention.dense
model.layers.17 post_attention_norm weight
model.layers.17 mlp.dense_h_to_4h weight
model.layers.17 mlp dense
error: mlp.dense
model.layers.17 mlp.dense_4h_to_h weight
model.layers.17 mlp dense
error: mlp.dense
model.layers.18 input_norm weight
model.layers.18 self_attention.query_key_value weight
model.layers.18 self_attention.query_key_value bias
model.layers.18 self_attention query
error: self_attention.query
model.layers.18 self_attention.dense weight
model.layers.18 self_attention dense
error: self_attention.dense
model.layers.18 post_attention_norm weight
model.layers.18 mlp.dense_h_to_4h weight
model.layers.18 mlp dense
error: mlp.dense
model.layers.18 mlp.dense_4h_to_h weight
model.layers.18 mlp dense
error: mlp.dense
model.layers.19 input_norm weight
model.layers.19 self_attention.query_key_value weight
model.layers.19 self_attention.query_key_value bias
model.layers.19 self_attention query
error: self_attention.query
model.layers.19 self_attention.dense weight
model.layers.19 self_attention dense
error: self_attention.dense
model.layers.19 post_attention_norm weight
model.layers.19 mlp.dense_h_to_4h weight
model.layers.19 mlp dense
error: mlp.dense
model.layers.19 mlp.dense_4h_to_h weight
model.layers.19 mlp dense
error: mlp.dense
model.layers.20 input_norm weight
model.layers.20 self_attention.query_key_value weight
model.layers.20 self_attention.query_key_value bias
model.layers.20 self_attention query
error: self_attention.query
model.layers.20 self_attention.dense weight
model.layers.20 self_attention dense
error: self_attention.dense
model.layers.20 post_attention_norm weight
model.layers.20 mlp.dense_h_to_4h weight
model.layers.20 mlp dense
error: mlp.dense
model.layers.20 mlp.dense_4h_to_h weight
model.layers.20 mlp dense
error: mlp.dense
model.layers.21 input_norm weight
model.layers.21 self_attention.query_key_value weight
model.layers.21 self_attention.query_key_value bias
model.layers.21 self_attention query
error: self_attention.query
model.layers.21 self_attention.dense weight
model.layers.21 self_attention dense
error: self_attention.dense
model.layers.21 post_attention_norm weight
model.layers.21 mlp.dense_h_to_4h weight
model.layers.21 mlp dense
error: mlp.dense
model.layers.21 mlp.dense_4h_to_h weight
model.layers.21 mlp dense
error: mlp.dense
model.layers.22 input_norm weight
model.layers.22 self_attention.query_key_value weight
model.layers.22 self_attention.query_key_value bias
model.layers.22 self_attention query
error: self_attention.query
model.layers.22 self_attention.dense weight
model.layers.22 self_attention dense
error: self_attention.dense
model.layers.22 post_attention_norm weight
model.layers.22 mlp.dense_h_to_4h weight
model.layers.22 mlp dense
error: mlp.dense
model.layers.22 mlp.dense_4h_to_h weight
model.layers.22 mlp dense
error: mlp.dense
model.layers.23 input_norm weight
model.layers.23 self_attention.query_key_value weight
model.layers.23 self_attention.query_key_value bias
model.layers.23 self_attention query
error: self_attention.query
model.layers.23 self_attention.dense weight
model.layers.23 self_attention dense
error: self_attention.dense
model.layers.23 post_attention_norm weight
model.layers.23 mlp.dense_h_to_4h weight
model.layers.23 mlp dense
error: mlp.dense
model.layers.23 mlp.dense_4h_to_h weight
model.layers.23 mlp dense
error: mlp.dense
Converting final layernorm
Converting LM head
Conversion from Megatron-LM to Transformers is done!
Saving config
Model weights saved in /mnt/raid/xujianjun/LLM_train/wjk/Megatron-LM/checkpoints/models--Qwen--Qwen1.5-0.5B-mg2hf41-aftertrain1_test/pytorch_model.bin


NOTE: Conversion is completed! Make sure to copy *.json files from Huggingface dir to /mnt/raid/xujianjun/LLM_train/wjk/Megatron-LM/checkpoints/models--Qwen--Qwen1.5-0.5B-mg2hf41-aftertrain1_test/
Exclude the model.safetensors.index.json file!
0 min 20 sec
``` 
训练和转换权重时设置的tp和pp都是4和1

**Comment by BlackBearBiscuit** [comment]
我有个疑惑，MLP层不应该是 gate_proj, up_proj和down_proj么，这么怎么只有 dense_h_to_4h, 那gate_proj呢？
