### ISSUE TITLE
When will support for converting Megatron models to Hugging Face model with pipeline parallelism enabled be available for Qwen1.5 models?

### ISSUE THREAD

**Issue by kaiwang13** [alibaba/Pai-Megatron-Patch#165]
I noticed that the `hf2mcore_1.5_v2.py` script in `Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/qwen` doesn't currently support pipeline parallelism. Are there any plans to add this feature?

**Comment by jerryli1981** [comment]
烦请pull下最新的代码再试试：https://github.com/alibaba/Pai-Megatron-Patch

**Comment by kaiwang13** [comment]
> 烦请pull下最新的代码再试试：https://github.com/alibaba/Pai-Megatron-Patch

hf2mcore似乎还是不支持pp>1。https://github.com/alibaba/Pai-Megatron-Patch/blob/cd7d1513393450fccb21e0e641207408affb1d61/toolkits/model_checkpoints_convertor/qwen/hf2mcore_1.5_v2.py#L536

**Comment by jerryli1981** [comment]
hf2mcore_1.5_v1.py版本其实是支持。v2和v1的区别是转换代码更容易维护且带精度校验功能

**Comment by kaiwang13** [comment]
> hf2mcore_1.5_v1.py版本其实是支持。v2和v1的区别是转换代码更容易维护且带精度校验功能

好的谢谢，那我去试一下v1的。

**Comment by kaiwang13** [comment]
> hf2mcore_1.5_v1.py版本其实是支持。v2和v1的区别是转换代码更容易维护且带精度校验功能

你好，这个转换脚本可以支持Qwen1.5-32B的GQA吗？

**Comment by kaiwang13** [comment]
> hf2mcore_1.5_v1.py版本其实是支持。v2和v1的区别是转换代码更容易维护且带精度校验功能

`hf2mcore_1.5_v1.py`似乎不支持PP>1同时如QWen1.5-32B一样有GQA的情况，在这里会出错：

```
Traceback (most recent call last):
  File "/Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/qwen/hf2mcore_1.5_v1.py", line 546, in <module>
    main()
  File "/Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/qwen/hf2mcore_1.5_v1.py", line 542, in main
    convert_checkpoint_from_transformers_to_megatron(args)
  File "/Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/qwen/hf2mcore_1.5_v1.py", line 448, in convert_checkpoint_from_transformers_to_megatron
    params = transformers_to_megatron_fix_query_key_value_ordering(
  File "/Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/qwen/hf2mcore_1.5_v1.py", line 242, in transformers_to_megatron_fix_query_key_value_ordering
    param = param.view(*current_shape)
RuntimeError: shape '[3, 40, 128, 5120]' is invalid for input of size 36700160
```
