### ISSUE TITLE
error: unrecognized arguments: --DDP-impl local

### ISSUE THREAD

**Issue by miangangzhen** [alibaba/Pai-Megatron-Patch#21]
Hi, I'm trying to run run_finetune_huggingface_chatglm.sh
but failed with this error
it seems like --DDP-impl is not a megatron arguments

finetune_huggingface_chatglm.py: error: unrecognized arguments: --DDP-impl local
[2023-09-18 08:19:24,158] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 2) local_rank: 0 (pid: 986) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.1.0a0+b5021ba', 'console_scripts', 'torchrun')())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 788, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by miangangzhen** [comment]
Megatron release 23.05 version works

https://github.com/NVIDIA/Megatron-LM
