### ISSUE TITLE
双节点A800-40G训练Qwen1.5-72B模型出错。

### ISSUE THREAD

**Issue by Renoshen** [alibaba/Pai-Megatron-Patch#228]
运行参数如下： sh run_pretrain_megatron_qwen.sh  dlc  /workspace/Pai-Megatron-Patch-dlc0.6  72B   1    8 1e-5   1e-6   128  128  421   fp16  8   1  sel  true   false  false   false  100000  /workspace/qwendatasets/wudao_qwenbpe_content_document   /workspace/qwen-ckpts/Qwen1.5-72B-hf-to-megatron-tp8-pp1/   100000000   10000   /workspace/output_megatron_qwen0.6
程序开始运行时前台打印内容如下：torchrun --nproc_per_node 8 --nnodes 2 --node_rank 1 --master_addr 10.0.0.5 --master_port 65433 ../llama2/pretrain_megatron_llama.py --save /workspace/output_megatron_qwen0.6/checkpoint/dlc-pretrain-megatron-gpt3-72B-lr-1e-5-bs-1-seqlen-128-pr-fp16-tp-8-pp-1-ac-sel-do-true-sp-false-tt-100000000-wt-10000 --split 98,2,0 --train-data-path /workspace/qwendatasets/wudao_qwenbpe_content_document --lr 1e-5 --min-lr 1e-6 --lr-decay-style linear --adam-beta1 0.9 --adam-beta2 0.95 --weight-decay 0.1 --clip-grad 1.0 --init-method-std 0.006 --lr-decay-iters 97656 --lr-warmup-iters 9 --train-iters 97656 --micro-batch-size 1 --global-batch-size 8 --num-layers 80 --hidden-size 8192 --num-attention-heads 64 --ffn-hidden-size 24576 --seq-length 128 --max-position-embeddings 128 --max-padding-length 128 --log-interval 1 --eval-interval 10000 --eval-iters 10 --save-interval 100000 --tensorboard-queue-size 1 --tensorboard-dir /workspace/output_megatron_qwen0.6/tensorboard/dlc-pretrain-megatron-gpt3-72B-lr-1e-5-bs-1-seqlen-128-pr-fp16-tp-8-pp-1-ac-sel-do-true-sp-false-tt-100000000-wt-10000_2024.05.13-15.17.48 --log-timers-to-tensorboard --log-batch-size-to-tensorboard --log-validation-ppl-to-tensorboard --tensor-model-parallel-size 8 --pipeline-model-parallel-size 1 --dataset LLama-Pretrain-Idxmap --no-load-optim --no-load-rng --num-workers 8 --seed 1234 --extra-vocab-size 421 --patch-tokenizer-type LLamaTokenizer --swiglu --normalization RMSNorm --use-llama2-rotary-position-embeddings --position-embedding-type rope --untie-embeddings-and-output-weights --rotary-base 1000000 --rotary-scale-factor 1 --fp16 --load /workspace/qwen-ckpts/Qwen1.5-72B-hf-to-megatron-tp8-pp1/ --recompute-activations --use-distributed-optimizer
从节点报错如下：
RuntimeError: Gloo connectFullMesh failed with [/opt/pytorch/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:144] no error
Traceback (most recent call last):
  File "/workspace/Pai-Megatron-Patch-dlc0.6/examples/qwen1_5/../llama2/pretrain_megatron_llama.py", line 125, in <module>
    pretrain(train_valid_test_datasets_provider, model_provider,
  File "/workspace/Pai-Megatron-Patch-dlc0.6/megatron_patch/training.py", line 90, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/workspace/Pai-Megatron-Patch-dlc0.6/Megatron-LM-231007/megatron/initialize.py", line 80, in initialize_megatron
    finish_mpu_init()
  File "/workspace/Pai-Megatron-Patch-dlc0.6/Megatron-LM-231007/megatron/initialize.py", line 60, in finish_mpu_init
    _initialize_distributed()
  File "/workspace/Pai-Megatron-Patch-dlc0.6/Megatron-LM-231007/megatron/initialize.py", line 209, in _initialize_distributed
    mpu.initialize_model_parallel(
  File "/workspace/Pai-Megatron-Patch-dlc0.6/Megatron-LM-231007/megatron/core/parallel_state.py", line 219, in initialize_model_parallel
    group_gloo = torch.distributed.new_group(ranks, backend="gloo")
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 86, in wrapper
    func_return = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3927, in new_group
    return _new_group_with_tag(ranks, timeout, backend, pg_options, None, use_local_synchronization=use_local_synchronization)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 3990, in _new_group_with_tag
    pg, pg_store = _new_process_group_helper(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 1295, in _new_process_group_helper
    backend_class = ProcessGroupGloo(backend_prefix_store, group_rank, group_size, timeout=timeout)
从报错看，貌似没有使用NCCL通信，二节点是安装了NCCL的nvcr.io/nvidia/pytorch官方镜像。
如何让程序使用NCCL呢？

**Comment by andy-yangz** [comment]
可以试试给运行脚本脚本前面加上
```bash
export NCCL_IB_GID_INDEX=3
export NCCL_IB_SL=3
export NCCL_SOCKET_IFNAME=bond1
export NCCL_IB_HCA=mlx5_bond_1,mlx5_bond_5,mlx5_bond_3,mlx5_bond_7,mlx5_bond_4,mlx5_bond_8,mlx5_bond_2,mlx5_bond_6
export GLOO_SOCKET_IFNAME=bond1 
```
