### ISSUE TITLE
数据预处理的脚本能在mac上运行吗，无法编译

### ISSUE THREAD

**Issue by shine10076** [alibaba/Pai-Megatron-Patch#276]
命令输出：
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting megatron-core==0.4.0
  Using cached https://mirrors.aliyun.com/pypi/packages/fd/b9/e85da25f4de43dad70d6fd1c21b88db085f471d5348c51cce05dc9e4b0ef/megatron_core-0.4.0.tar.gz (154 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/Users/qianyu/miniconda3/envs/Pai-Megatron-Patch/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/qianyu/miniconda3/envs/Pai-Megatron-Patch/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/qianyu/miniconda3/envs/Pai-Megatron-Patch/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/zj/_58s8xx55pj2t8dw3w8j_lgm0000gp/T/pip-build-env-l_62dzm8/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/private/var/folders/zj/_58s8xx55pj2t8dw3w8j_lgm0000gp/T/pip-build-env-l_62dzm8/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/zj/_58s8xx55pj2t8dw3w8j_lgm0000gp/T/pip-build-env-l_62dzm8/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/zj/_58s8xx55pj2t8dw3w8j_lgm0000gp/T/pip-build-env-l_62dzm8/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 52, in <module>
        File "<string>", line 45, in req_file
      FileNotFoundError: [Errno 2] No such file or directory: 'megatron/core/requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

系统环境：
macbook pro m3

**Comment by jerryli1981** [comment]
您好，不能在mac上运行的，只能在linux系统上运行
