### ISSUE TITLE
[[: not found Zarr-based strategies will not be registered because of missing packages Traceback (most recent call last)

### ISSUE THREAD

**Issue by aJupyter** [alibaba/Pai-Megatron-Patch#346]
follow：https://github.com/alibaba/Pai-Megatron-Patch/blob/main/examples/qwen1_5/README.md#megatron-lm-dense%E6%A8%A1%E5%9E%8B%E6%A0%BC%E5%BC%8F%E8%BD%AC%E6%8D%A2

报错如下：看起来是pytorch_model.bin和safetensor不兼容？
[[: not found Zarr-based strategies will not be registered because of missing packages Traceback (most recent call last):   File "/workspace/Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/qwen/hf2megatron_qwen1.0.py", line 1008, in <module>     main()   File "/workspace/Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/qwen/hf2megatron_qwen1.0.py", line 1004, in main     convert_checkpoint_from_transformers_to_megatron(args)   File "/workspace/Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/qwen/hf2megatron_qwen1.0.py", line 382, in convert_checkpoint_from_transformers_to_megatron     hf_state_dict = torch.load(os.path.join(args.load_path, checkpoint_name), map_location="cpu")   File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 996, in load     with _open_file_like(f, 'rb') as opened_file:   File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 445, in _open_file_like     return _open_file(name_or_buffer, mode)   File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 426, in __init__     super().__init__(open(name, mode)) FileNotFoundError: [Errno 2] No such file or directory: '/mnt/qwen-ckpts/Qwen1.5-0.5B/pytorch_model.bin'

**Comment by aJupyter** [comment]
已解决，降低transformers包版本即可。
预训练报错：AttributeError: '_Qwen2Tokenizer' object has no attribute 'bos_token_id'
