### ISSUE TITLE
cannot import name 'TEDotProductAttentionMLA' when running `examples/deepseek_v2/run_mcore_deepseek.sh`

### ISSUE THREAD

**Issue by dreasysnail** [alibaba/Pai-Megatron-Patch#359]
Thank you for the great project! When I run `examples/deepseek_v2/run_mcore_deepseek.sh` I got an error as below:

```
Traceback (most recent call last):
  File "/mnt/task_runtime/examples/deepseek_v2/pretrain_deepseek.py", line 37, in <module>
    from megatron_patch.model.deepseek_v2.layer_specs import (
  File "/mnt/task_runtime/megatron_patch/model/deepseek_v2/layer_specs.py", line 19, in <module>
    from megatron.core.transformer.custom_layers.transformer_engine import (
ImportError: cannot import name 'TEDotProductAttentionMLA' from 'megatron.core.transformer.custom_layers.transformer_engine' (/mnt/task_runtime/PAI-Megatron-LM-240718/megatron/core/transformer/custom_layers/transformer_engine.py)
```

It appears that in [this link](https://github.com/alibaba/Pai-Megatron-Patch/blob/9d3e557b4d5f386a456a49da23aa47af737baaf3/megatron_patch/model/deepseek_v2/layer_specs.py#L21) the code is attempting to import 'TEDotProductAttentionMLA', but when I checked the [`megatron.core.transformer.custom_layers.transformer_engine`](https://github.com/jerryli1981/PAI-Megatron-LM-240718/blob/7765c381d5af76f97834934a67b1e43afece02ad/megatron/core/transformer/custom_layers/transformer_engine.py) file, I did not find 'TEDotProductAttentionMLA'.

Any help appreciated!

**Comment by dreasysnail** [comment]
@Jiayi-Pan

**Comment by NiuMa-1234** [comment]
Hi, have you solved the problem? I 'm trying to use TEDotProductAttentionMLA, too, and I found the difference between it and its original TEDotProductAttention is only the definition of kv_channels. So I just manually change the  kv_channels  and keep using the TEDotProductAttention. I'm not sure if this's right.

**Comment by Jiayi-Pan** [comment]
Hi we've solved the issue. You can just update the git submodule to the latest version

**Comment by NiuMa-1234** [comment]
> Hi we've solved the issue. You can just update the git submodule to the latest version

Hi, I've tested the latest TEDotProductAttentionMLA but I found the speed  has dropped a bit (from 5.9 tokens/s to 4.4 on 8*8B model). Would this be normal?

**Comment by jerryli1981** [comment]
您好，DeepSeek-V2我们刚刚进行了升级改进，烦请更新下最新版，谢谢
