### ISSUE TITLE
Qwen2.5-32B模型从hf转到macro失败

### ISSUE THREAD

**Issue by cingtiye** [alibaba/Pai-Megatron-Patch#394]
转14B正常转，转32B报下面的错误
DEVICE: 8张H100-80gb

```bash
oom for huggingface model forward
[rank0]: Traceback (most recent call last):
[rank0]:   File "/data1/Projects/Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/qwen/hf2mcore_qwen2_dense_and_moe_gqa.py", line 951, in <module>
[rank0]:     main()
[rank0]:   File "/data1/Projects/Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/qwen/hf2mcore_qwen2_dense_and_moe_gqa.py", line 947, in main
[rank0]:     check_hf_mg_forward(hf_model, mg_model, args)
[rank0]:   File "/data1/Projects/Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/qwen/hf2mcore_qwen2_dense_and_moe_gqa.py", line 901, in check_hf_mg_forward
[rank0]:     mglogits = mgmodel(input_ids=input_ids, attention_mask=attention_mask, position_ids=position_ids)

[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1552, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1561, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/data1/Projects/Pai-Megatron-Patch/megatron_patch/model/qwen2/model.py", line 219, in forward
[rank0]:     logits, _ = self.output_layer(hidden_states, weight=output_weight)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1552, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1602, in _call_impl
[rank0]:     result = forward_call(*args, **kwargs)
[rank0]:   File "/data1/Projects/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/core/tensor_parallel/layers.py", line 896, in forward
[rank0]:     output_parallel = self._forward_impl(
[rank0]:   File "/data1/Projects/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/core/tensor_parallel/layers.py", line 653, in linear_with_grad_accumulation_and_async_allreduce
[rank0]:     return LinearWithGradAccumulationAndAsyncCommunication.apply(*args)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 573, in apply
[rank0]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py", line 454, in decorate_fwd'

[rank0]:     return fwd(*args, **kwargs)
[rank0]:   File "/data1/Projects/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/core/tensor_parallel/layers.py", line 422, in forward
[rank0]:     output = torch.matmul(total_input, weight.t())
[rank0]: RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
[rank0]:[W1207 13:36:48.680004198 ProcessGroupNCCL.cpp:1187] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.4.0a0+3bcc3cddb5.nv24.7', 'console_scripts', 'torchrun')())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 900, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 891, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
hf2mcore_qwen2_dense_and_moe_gqa.py FAILED
------------------------------------------------------------

```

**Comment by lostkevin** [comment]
转换check forward使用单卡，32B可能会遇到OOM，可以关掉check或者加上cpu-initialization开关（参考72B）试试

**Comment by cingtiye** [comment]
> 转换check forward使用单卡，32B可能会遇到OOM，可以关掉check或者加上cpu-initialization开关（参考72B）试试

关掉check是指把assert屏蔽？“加上cpu-initialization开关（参考72B）“可以给个链接吗

**Comment by cingtiye** [comment]
> 转换check forward使用单卡，32B可能会遇到OOM，可以关掉check或者加上cpu-initialization开关（参考72B）试试

加上cpu-initialization跑的好慢
