### ISSUE TITLE
--reset_position_ids bug

### ISSUE THREAD

**Issue by haorannlp** [alibaba/Pai-Megatron-Patch#406]
- 模型： qwen 2.5 3B
- 参数：
```
ENV=dsw                          # 运行环境配置开关: dsw单机训练训练，dlc表示多机训练环境
MODEL_SIZE=3B                   # 模型结构参数量级: 0.5B/1.5B/3B/7B/14B/32B/72B
BATCH_SIZE=2                   # 一次迭代一个数据并行内的样本数
GLOBAL_BATCH_SIZE=768            # 一次迭代多个数据并行的总样本数
LR=3e-5                          # 学习率
MIN_LR=3e-6                       # 最小学习率
SEQ_LEN=4096                      # 序列长度
PAD_LEN=4096                      # Padding长度
PR=bf16                         # 训练精度: fp16, bf16, fp8
TP=1                        # 模型并行度
PP=1                        # 流水并行度
CP=1                        # 上下文并行度
SP=true                        # 是否使用序列并行: true, false
DO=true                        # 是否使用Megatron版Zero-1降显存优化器: true, false
FL=true                       # 是否优先使用Flash Attention: true, false
SFT=false                       # 是否执行微调训练: true, false
AC=sel                        # 激活检查点模式: sel, full, offload, false
OPTIMIZER_OFFLOAD=false         # 是否启用Offload optimizer: false, static, auto
```

- 问题：为了pre-train的时候使用sequence packing，开启`--reset-position-ids`，但遇到error:
```
[rank5]: Traceback (most recent call last):
[rank5]:   File "/opt/tiger/Pai-Megatron-Patch/examples/qwen2_5/../qwen2/pretrain_qwen.py", line 290, in <module>
[rank5]:     pretrain(
[rank5]:   File "/opt/tiger/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/training/training.py", line 326, in pretrain
[rank5]:     iteration, num_floating_point_operations_so_far = train(
[rank5]:                                                       ^^^^^^
[rank5]:   File "/opt/tiger/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/training/training.py", line 1249, in train
[rank5]:     loss_dict, skipped_iter, grad_norm, num_zeros_in_grad = train_step(
[rank5]:                                                             ^^^^^^^^^^^
[rank5]:   File "/opt/tiger/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/training/training.py", line 690, in train_step
[rank5]:     losses_reduced = forward_backward_func(
[rank5]:                      ^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/opt/tiger/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/core/pipeline_parallel/schedules.py", line 395, in forward_backward_no_pipelining
[rank5]:     output_tensor, num_tokens = forward_step(
[rank5]:                                 ^^^^^^^^^^^^^
[rank5]:   File "/opt/tiger/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/core/pipeline_parallel/schedules.py", line 219, in forward_step
[rank5]:     output_tensor, loss_func = forward_step_func(data_iterator, model)
[rank5]:                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/opt/tiger/Pai-Megatron-Patch/examples/qwen2_5/../qwen2/pretrain_qwen.py", line 219, in forward_step
[rank5]:     output_tensor = model(tokens, position_ids, attention_mask, labels=labels, packed_seq_params=packed_seq_params)
[rank5]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1603, in _call_impl
[rank5]:     result = forward_call(*args, **kwargs)
[rank5]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/opt/tiger/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/core/distributed/distributed_data_parallel.py", line 204, in forward
[rank5]:     return self.module(*inputs, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1603, in _call_impl
[rank5]:     result = forward_call(*args, **kwargs)
[rank5]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/opt/tiger/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/legacy/model/module.py", line 189, in forward
[rank5]:     outputs = self.module(*inputs, **kwargs)
[rank5]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1603, in _call_impl
[rank5]:     result = forward_call(*args, **kwargs)
[rank5]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/opt/tiger/Pai-Megatron-Patch/megatron_patch/model/qwen2/model.py", line 203, in forward
[rank5]:     hidden_states = self.decoder(
[rank5]:                     ^^^^^^^^^^^^^
[rank5]:   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1603, in _call_impl
[rank5]:     result = forward_call(*args, **kwargs)
[rank5]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/opt/tiger/Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer_block.py", line 402, in forward
[rank5]:     hidden_states, context = layer(
[rank5]:                              ^^^^^^
[rank5]:   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1603, in _call_impl
[rank5]:     result = forward_call(*args, **kwargs)
[rank5]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/opt/tiger/Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer_layer.py", line 189, in forward
[rank5]:     attention_output_with_bias = self.self_attention(
[rank5]:                                  ^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank5]:     return self._call_impl(*args, **kwargs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1603, in _call_impl
[rank5]:     result = forward_call(*args, **kwargs)
[rank5]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/opt/tiger/Pai-Megatron-Patch/megatron_patch/model/qwen2/transformer/attention.py", line 300, in forward
[rank5]:     query = apply_rotary_pos_emb(
[rank5]:             ^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/opt/tiger/Pai-Megatron-Patch/PAI-Megatron-LM-240718/megatron/core/models/common/embeddings/rotary_pos_embedding.py", line 247, in apply_rotary_pos_emb
[rank5]:     return fused_apply_rotary_pos_emb_thd(t, cu_seqlens, freqs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/usr/local/lib/python3.11/dist-packages/apex/transformer/functional/fused_rope.py", line 211, in fused_apply_rotary_pos_emb_thd
[rank5]:     return FusedRoPETHDFunc.apply(t, cu_seqlens, freqs)
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/usr/local/lib/python3.11/dist-packages/torch/autograd/function.py", line 574, in apply
[rank5]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
[rank5]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]:   File "/usr/local/lib/python3.11/dist-packages/apex/transformer/functional/fused_rope.py", line 170, in forward
[rank5]:     output = fused_rotary_positional_embedding.forward_thd(
[rank5]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank5]: RuntimeError: expected 3D tensor
```

上述错误的bug中提到的函数`fused_apply_rotary_pos_emb_thd(t, cu_seqlens, freqs)` 的输入shape为：`torch.Size([4096, 2, 16, 128])`，非`3D tensor`
检查发现问题出在`Pai-Megatron-Patch/megatron_patch/model/llama3/transformer/attention.py`中这段代码：
```
        key, value, rotary_pos_emb, attn_mask_type = self._adjust_key_value_for_inference(
            inference_params, key, value, rotary_pos_emb
        )

        if packed_seq_params is not None:
            query = query.squeeze(1)
            key = key.squeeze(1)
            value = value.squeeze(1)
```
query shape为：` torch.Size([4096, 2, 16, 128])`，但是if语句中的` query = query.squeeze(1)`在bs>1的情况下并不能squeeze成3D tensor

**Comment by haorannlp** [comment]
bs=1

**Comment by Eisenhower** [comment]
你好，我SFT时也遇到了同样的问题，想问下除了设置bs=1，还有其它解法吗？毕竟bs=1时，GPU算力、存储利用率有些低，单条seqlen设置太大又容易OOM

**Comment by gdragone1** [comment]
想问下这个有解决了吗？不再是只能bs=1了吧？
