### ISSUE TITLE
AttributeError: 'torch._C._distributed_c10d.Options' object has no attribute 'config'

### ISSUE THREAD

**Issue by jiejie1993** [alibaba/Pai-Megatron-Patch#44]
**环境：**
torch                    2.0.1+cu118
python                 3.10
Pai-megatron-patch  0.5.2
Megatron-LM      23.06_pt_23.09分支

**启动脚本：**
使用llama2-13B模型进行megatron微调，调用的脚本为
`sh run_pretrain_megatron_llama.sh \
dsw \
/mnt/nas/gyj/software/Megatron-LM \
/mnt/nas/gyj/Pai-Megatron-Patch-main \
13B \
1 \
8 \
1e-5 \
1e-6 \
2048 \
2048 \
0 \
bf16 \
1 \
1 \
sel \
true \
true \
true \
100000 \
${DATASET_DIR} \
${SOURCE_MODEL_PATH} \
10000000000 \
100000000 \
${OUT_MODEL_PATH}`

**问题：**
发生如下报错：
`Traceback (most recent call last):
  File "/mnt/nas/gyj/Pai-Megatron-Patch-main/examples/llama2/pretrain_megatron_llama.py", line 96, in <module>
    pretrain(train_valid_test_datasets_provider,
  File "/mnt/nas/gyj/Pai-Megatron-Patch-main/megatron_patch/training.py", line 86, in pretrain
    pretrain(train_valid_test_datasets_provider,
  File "/mnt/nas/gyj/Pai-Megatron-Patch-main/megatron_patch/training.py", line 86, in pretrain
    pretrain(train_valid_test_datasets_provider,
  File "/mnt/nas/gyj/Pai-Megatron-Patch-main/megatron_patch/training.py", line 86, in pretrain
    pretrain(train_valid_test_datasets_provider,
  File "/mnt/nas/gyj/Pai-Megatron-Patch-main/megatron_patch/training.py", line 86, in pretrain
    pretrain(train_valid_test_datasets_provider,
  File "/mnt/nas/gyj/Pai-Megatron-Patch-main/megatron_patch/training.py", line 86, in pretrain
    pretrain(train_valid_test_datasets_provider,
  File "/mnt/nas/gyj/Pai-Megatron-Patch-main/megatron_patch/training.py", line 86, in pretrain
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/mnt/nas/gyj/software/Megatron-LM/megatron/initialize.py", line 76, in initialize_megatron
    initialize_megatron(extra_args_provider=extra_args_provider,
  File "/mnt/nas/gyj/software/Megatron-LM/megatron/initialize.py", line 76, in initialize_megatron
    finish_mpu_init()
  File "/mnt/nas/gyj/software/Megatron-LM/megatron/initialize.py", line 56, in finish_mpu_init
    _initialize_distributed()
  File "/mnt/nas/gyj/software/Megatron-LM/megatron/initialize.py", line 185, in _initialize_distributed
    mpu.initialize_model_parallel(args.tensor_model_parallel_size,
  File "/mnt/nas/gyj/software/Megatron-LM/megatron/core/parallel_state.py", line 172, in initialize_model_parallel
    nccl_options.config.cga_cluster_size = int(os.getenv("MEGATRON_CORE_DP_CGA_GROUPS", 4))
AttributeError: 'torch._C._distributed_c10d.Options' object has no attribute 'config'`

**Comment by jerryli1981** [comment]
git clone https://github.com/alibaba/Pai-Megatron-Patch.git 
git clone https://github.com/NVIDIA/Megatron-LM.git
应该就可以了，主要是Patch的版本和Megatron LM的版本没匹配起来
