### ISSUE TITLE
Training baichuan2 13b, when pp>1, it will nanloss when flash attention is turned off.

### ISSUE THREAD

**Issue by uygnef** [alibaba/Pai-Megatron-Patch#60]
It might be an issue with the attention mask.

The startup script is:
`sh run_pretrain_megatron_baichuan.sh dsw /workdir/fengyu05/Pai-Megatron-Patch 13B 1 8 1e-5 1e-6 4096 4096 0 bf16 4 2 sel true false true false 100000 /mnt/dolphinfs/hdd_pool/docker/share/llama_efficient/comparison_gpt4_data_en.json /mnt/dolphinfs/hdd_pool/docker/user/fengyu05/model/baichuan-13b-base-hf-to-megatron-tp4-pp2_1 100000000 10000 output_baichuan2`

error is:
```
Traceback (most recent call last):
    assert not total_norm.isnan(), (
  File "/workdir/fengyu05/Pai-Megatron-Patch/examples/baichuan2/pretrain_megatron_baichuan.py", line 101, in <module>
AssertionError: Rank 3: found NaN in local grad norm in backwards pass. Device: 3, node: set-zw04-kubernetes-pc133.mt
    pretrain(train_valid_test_datasets_provider,
  File "/workdir/fengyu05/Pai-Megatron-Patch/megatron_patch/training.py", line 152, in pretrain
    iteration = train(forward_step_func,
  File "/workdir/fengyu05/Pai-Megatron-Patch/megatron_patch/training.py", line 652, in train
    train_step(forward_step_func,
  File "/workdir/fengyu05/Pai-Megatron-Patch/megatron_patch/training.py", line 385, in train_step
    update_successful, grad_norm, num_zeros_in_grad = optimizer.step(args, timers)
  File "/usr/local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workdir/fengyu05/Pai-Megatron-Patch/Megatron-LM-main/megatron/optimizer/optimizer.py", line 329, in step
    grad_norm = self.clip_grad_norm(self.clip_grad,
  File "/workdir/fengyu05/Pai-Megatron-Patch/Megatron-LM-main/megatron/optimizer/optimizer.py", line 111, in clip_grad_norm
    return clip_grad_norm_fp32(
  File "/workdir/fengyu05/Pai-Megatron-Patch/Megatron-LM-main/megatron/optimizer/clip_grads.py", line 98, in clip_grad_norm_fp32
    assert not total_norm.isnan(), (
AssertionError: Rank 1: found NaN in local grad norm in backwards pass. Device: 1, node: set-zw04-kubernetes-pc133.mt
```

**Comment by jerryli1981** [comment]
pull下最新的代码试试

**Comment by uygnef** [comment]
> pull下最新的代码试试

嗯，最新的代码没问题了
