### ISSUE TITLE
模型转换脚本从megatron转为huggingface格式存在不匹配

### ISSUE THREAD

**Issue by ctomx837** [alibaba/Pai-Megatron-Patch#65]
使用llama2模型转换脚本，从megatron转为huggingface格式时，显示转换失败：
Traceback (most recent call last):
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-speech/users/chenxiang22/e2e/llm/llm_train_envir/Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/llama/checkpoint_reshaping_and_interoperability.py", line 1102, in <module>
    main()
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-speech/users/chenxiang22/e2e/llm/llm_train_envir/Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/llama/checkpoint_reshaping_and_interoperability.py", line 1096, in main
    convert_checkpoint_from_megatron_to_transformers(args)
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-speech/users/chenxiang22/e2e/llm/llm_train_envir/Pai-Megatron-Patch/toolkits/model_checkpoints_convertor/llama/checkpoint_reshaping_and_interoperability.py", line 1019, in convert_checkpoint_from_megatron_to_transformers
    out_name = megatron_to_transformers[op_name]
KeyError: 'self_attention.query'

采用megatron-deepspeed训练的llama2模型，k，q，v权重矩阵名称为：'self_attention.query.weight': torch.Size([2048, 2048]), 'self_attention.key_value.weight': torch.Size([1024, 2048])
但是看到转换脚本中只对self_attention.query_key_value做了转化，是没有考虑到这种情况吗，有没有其他解决方式？

**Comment by lwmlyy** [comment]
你好，这个转换脚本只适用于patch训练出来的llama2模型，且需要对应版本。麻烦把具体的信息发一下。
